name: release-dev

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read
  packages: write
  security-events: write

# Concurrency cancellation
concurrency:
  group: release-dev-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dev:
    uses: ./.github/workflows/release-reusable.yaml
    with:
      release-tag: dev
      checkout-ref: ${{ github.ref }}
      artifact-prefix: trivy-dev-reports
      publish: true
      security-scan: false
      notify: false
    secrets: inherit
